// File generated by FlutterFire CLI (mock placeholders for initial setup).
// To generate the real configurations, run: flutterfire configure
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9GhLJHv3jucd9Uht6MFu9vDX23cC6et4',
    appId: '1:505033307715:android:6ceddb3c759d7a9a8c46f6',
    messagingSenderId: '505033307715',
    projectId: 'dayscore-health-app',
    authDomain: 'dayscore-health-app.firebaseapp.com',
    storageBucket: 'dayscore-health-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9GhLJHv3jucd9Uht6MFu9vDX23cC6et4',
    appId: '1:505033307715:android:6ceddb3c759d7a9a8c46f6',
    messagingSenderId: '505033307715',
    projectId: 'dayscore-health-app',
    storageBucket: 'dayscore-health-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9GhLJHv3jucd9Uht6MFu9vDX23cC6et4',
    appId: '1:505033307715:android:6ceddb3c759d7a9a8c46f6',
    messagingSenderId: '505033307715',
    projectId: 'dayscore-health-app',
    storageBucket: 'dayscore-health-app.firebasestorage.app',
    iosBundleId: 'com.example.dayscore',
  );
}
