import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../core/constants/app_colors.dart';
import '../../../core/constants/app_strings.dart';
import '../../../core/router/route_names.dart';
import '../../../widgets/common/app_scaffold.dart';
import '../../../widgets/common/glass_card.dart';
import '../../../widgets/common/gradient_button.dart';
import '../domain/user_model.dart';
import 'auth_providers.dart';

class RegisterScreen extends ConsumerStatefulWidget {
  const RegisterScreen({super.key});

  @override
  ConsumerState<RegisterScreen> createState() => _RegisterScreenState();
}

class _RegisterScreenState extends ConsumerState<RegisterScreen> {
  final _formKey1 = GlobalKey<FormState>();
  final _formKey2 = GlobalKey<FormState>();

  int _currentStep = 0;
  final PageController _pageController = PageController();

  // Step 1 Controllers
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();

  // Step 2 Controllers
  final _ageController = TextEditingController();
  String _selectedGender = 'Prefer not to say';
  String _selectedWorkType = 'Desk Job (Sedentary)';
  double _stressLevel = 5.0;
  double _sleepTarget = 8.0;
  int _fitnessTarget = 8000;
  final List<String> _selectedGoals = [];

  final List<String> _genderOptions = [
    'Male',
    'Female',
    'Non-binary',
    'Prefer not to say'
  ];

  final List<String> _workTypeOptions = [
    'Student',
    'Desk Job (Sedentary)',
    'Active Work (Standing/Moving)',
    'Highly Active'
  ];

  final List<String> _goalOptions = [
    'Reduce Stress',
    'Improve Sleep',
    'Increase Steps',
    'Optimize Habits',
    'Enhance Focus'
  ];

  @override
  void dispose() {
    _nameController.dispose();
    _emailController.dispose();
    _passwordController.dispose();
    _ageController.dispose();
    _pageController.dispose();
    super.dispose();
  }

  void _nextStep() {
    if (_formKey1.currentState!.validate()) {
      setState(() {
        _currentStep = 1;
      });
      _pageController.nextPage(
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeInOut,
      );
    }
  }

  void _previousStep() {
    setState(() {
      _currentStep = 0;
    });
    _pageController.previousPage(
      duration: const Duration(milliseconds: 300),
      curve: Curves.easeInOut,
    );
  }

  void _onSignUp() async {
    if (_formKey2.currentState!.validate()) {
      if (_selectedGoals.isEmpty) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Please select at least one wellness goal.'),
            backgroundColor: AppColors.error,
          ),
        );
        return;
      }

      final profile = UserModel(
        uid: '', // Generated by Firebase Auth on signup
        email: _emailController.text.trim(),
        name: _nameController.text.trim(),
        age: int.tryParse(_ageController.text) ?? 20,
        gender: _selectedGender,
        goals: _selectedGoals,
        stressLevel: _stressLevel.toInt(),
        sleepTarget: _sleepTarget,
        fitnessTarget: _fitnessTarget,
        workStudyType: _selectedWorkType,
        createdAt: DateTime.now(),
      );

      final success = await ref.read(authControllerProvider.notifier).signUp(
            _emailController.text.trim(),
            _passwordController.text.trim(),
            profile,
          );

      if (success && mounted) {
        context.goNamed(RouteNames.dashboard);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final authState = ref.watch(authControllerProvider);
    final isLoading = authState.isLoading;

    ref.listen<AsyncValue<void>>(authControllerProvider, (previous, next) {
      next.whenOrNull(
        error: (error, stackTrace) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                error.toString().replaceAll('Exception: ', ''),
                style: const TextStyle(color: Colors.white),
              ),
              backgroundColor: AppColors.error,
            ),
          );
        },
      );
    });

    return AppScaffold(
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  IconButton(
                    icon: const Icon(Icons.arrow_back),
                    onPressed: () {
                      if (_currentStep == 1) {
                        _previousStep();
                      } else {
                        context.pop();
                      }
                    },
                  ),
                  Text(
                    'Step ${_currentStep + 1} of 2',
                    style: const TextStyle(color: AppColors.cyan, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
            ),
            Expanded(
              child: PageView(
                controller: _pageController,
                physics: const NeverScrollableScrollPhysics(),
                children: [
                  _buildStep1(isLoading),
                  _buildStep2(isLoading),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStep1(bool isLoading) {
    return SingleChildScrollView(
      padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0),
      child: Form(
        key: _formKey1,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              AppStrings.registerTitle,
              style: Theme.of(context).textTheme.headlineLarge,
            ),
            const SizedBox(height: 8.0),
            Text(
              AppStrings.registerSubtitle,
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    color: AppColors.textSecondary,
                  ),
            ),
            const SizedBox(height: 32.0),
            GlassCard(
              child: Column(
                children: [
                  TextFormField(
                    controller: _nameController,
                    enabled: !isLoading,
                    style: const TextStyle(color: AppColors.textPrimary),
                    decoration: const InputDecoration(
                      labelText: AppStrings.nameLabel,
                      labelStyle: TextStyle(color: AppColors.textSecondary),
                      enabledBorder: UnderlineInputBorder(
                        borderSide: BorderSide(color: AppColors.glassBorder),
                      ),
                      focusedBorder: UnderlineInputBorder(
                        borderSide: BorderSide(color: AppColors.cyan),
                      ),
                      prefixIcon: Icon(Icons.person_outline, color: AppColors.textSecondary),
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter your name';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 20.0),
                  TextFormField(
                    controller: _emailController,
                    enabled: !isLoading,
                    keyboardType: TextInputType.emailAddress,
                    style: const TextStyle(color: AppColors.textPrimary),
                    decoration: const InputDecoration(
                      labelText: AppStrings.emailLabel,
                      labelStyle: TextStyle(color: AppColors.textSecondary),
                      enabledBorder: UnderlineInputBorder(
                        borderSide: BorderSide(color: AppColors.glassBorder),
                      ),
                      focusedBorder: UnderlineInputBorder(
                        borderSide: BorderSide(color: AppColors.cyan),
                      ),
                      prefixIcon: Icon(Icons.email_outlined, color: AppColors.textSecondary),
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter your email';
                      }
                      if (!RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$').hasMatch(value.trim())) {
                        return 'Please enter a valid email address';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 20.0),
                  TextFormField(
                    controller: _passwordController,
                    obscureText: true,
                    enabled: !isLoading,
                    style: const TextStyle(color: AppColors.textPrimary),
                    decoration: const InputDecoration(
                      labelText: AppStrings.passwordLabel,
                      labelStyle: TextStyle(color: AppColors.textSecondary),
                      enabledBorder: UnderlineInputBorder(
                        borderSide: BorderSide(color: AppColors.glassBorder),
                      ),
                      focusedBorder: UnderlineInputBorder(
                        borderSide: BorderSide(color: AppColors.cyan),
                      ),
                      prefixIcon: Icon(Icons.lock_outline, color: AppColors.textSecondary),
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter your password';
                      }
                      if (value.trim().length < 6) {
                        return 'Password must be at least 6 characters';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 32.0),
                  GradientButton(
                    text: 'Continue Setup',
                    onPressed: _nextStep,
                  ),
                ],
              ),
            ),
            const SizedBox(height: 32.0),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Text(
                  "Already have an account? ",
                  style: TextStyle(color: AppColors.textSecondary),
                ),
                GestureDetector(
                  onTap: () => context.pop(),
                  child: const Text(
                    'Sign In',
                    style: TextStyle(
                      color: AppColors.lime,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildStep2(bool isLoading) {
    return SingleChildScrollView(
      padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0),
      child: Form(
        key: _formKey2,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Wellness Profile',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
            const SizedBox(height: 8.0),
            const Text(
              'We use this to customize recommendations and predict your wellness metrics.',
              style: TextStyle(color: AppColors.textSecondary),
            ),
            const SizedBox(height: 24.0),
            GlassCard(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  // Age input
                  TextFormField(
                    controller: _ageController,
                    keyboardType: TextInputType.number,
                    enabled: !isLoading,
                    style: const TextStyle(color: AppColors.textPrimary),
                    decoration: const InputDecoration(
                      labelText: 'Age',
                      labelStyle: TextStyle(color: AppColors.textSecondary),
                      enabledBorder: UnderlineInputBorder(
                        borderSide: BorderSide(color: AppColors.glassBorder),
                      ),
                      focusedBorder: UnderlineInputBorder(
                        borderSide: BorderSide(color: AppColors.cyan),
                      ),
                      prefixIcon: Icon(Icons.cake_outlined, color: AppColors.textSecondary),
                    ),
                    validator: (value) {
                      if (value == null || value.trim().isEmpty) {
                        return 'Please enter your age';
                      }
                      if (int.tryParse(value) == null || int.parse(value) <= 0) {
                        return 'Please enter a valid age';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 20.0),

                  // Gender Dropdown
                  DropdownButtonFormField<String>(
                    initialValue: _selectedGender,
                    dropdownColor: AppColors.surfaceDark,
                    style: const TextStyle(color: AppColors.textPrimary),
                    decoration: const InputDecoration(
                      labelText: 'Gender',
                      labelStyle: TextStyle(color: AppColors.textSecondary),
                      enabledBorder: UnderlineInputBorder(
                        borderSide: BorderSide(color: AppColors.glassBorder),
                      ),
                      prefixIcon: Icon(Icons.wc_outlined, color: AppColors.textSecondary),
                    ),
                    items: _genderOptions.map((String value) {
                      return DropdownMenuItem<String>(
                        value: value,
                        child: Text(value),
                      );
                    }).toList(),
                    onChanged: isLoading
                        ? null
                        : (newValue) {
                            setState(() {
                              _selectedGender = newValue!;
                            });
                          },
                  ),
                  const SizedBox(height: 20.0),

                  // Work type Dropdown
                  DropdownButtonFormField<String>(
                    initialValue: _selectedWorkType,
                    dropdownColor: AppColors.surfaceDark,
                    style: const TextStyle(color: AppColors.textPrimary),
                    decoration: const InputDecoration(
                      labelText: 'Daily Activity / Work Level',
                      labelStyle: TextStyle(color: AppColors.textSecondary),
                      enabledBorder: UnderlineInputBorder(
                        borderSide: BorderSide(color: AppColors.glassBorder),
                      ),
                      prefixIcon: Icon(Icons.work_outline, color: AppColors.textSecondary),
                    ),
                    items: _workTypeOptions.map((String value) {
                      return DropdownMenuItem<String>(
                        value: value,
                        child: Text(value),
                      );
                    }).toList(),
                    onChanged: isLoading
                        ? null
                        : (newValue) {
                            setState(() {
                              _selectedWorkType = newValue!;
                            });
                          },
                  ),
                  const SizedBox(height: 24.0),

                  // Wellness Goals Choice Chips
                  const Text(
                    'Wellness Goals (Select all that apply)',
                    style: TextStyle(color: AppColors.textSecondary, fontWeight: FontWeight.bold, fontSize: 13),
                  ),
                  const SizedBox(height: 8.0),
                  Wrap(
                    spacing: 8.0,
                    runSpacing: 4.0,
                    children: _goalOptions.map((goal) {
                      final isSelected = _selectedGoals.contains(goal);
                      return FilterChip(
                        label: Text(goal),
                        selected: isSelected,
                        labelStyle: TextStyle(
                          color: isSelected ? AppColors.surfaceDark : AppColors.textPrimary,
                          fontSize: 12,
                          fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                        ),
                        selectedColor: AppColors.cyan,
                        backgroundColor: AppColors.surface,
                        checkmarkColor: AppColors.surfaceDark,
                        onSelected: isLoading
                            ? null
                            : (selected) {
                                setState(() {
                                  if (selected) {
                                    _selectedGoals.add(goal);
                                  } else {
                                    _selectedGoals.remove(goal);
                                  }
                                });
                              },
                      );
                    }).toList(),
                  ),
                  const SizedBox(height: 24.0),

                  // Baseline Stress Level slider
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text(
                        'Baseline Stress Level',
                        style: TextStyle(color: AppColors.textSecondary, fontSize: 13),
                      ),
                      Text(
                        '${_stressLevel.toInt()}/10',
                        style: const TextStyle(color: AppColors.purple, fontWeight: FontWeight.bold),
                      ),
                    ],
                  ),
                  Slider(
                    value: _stressLevel,
                    min: 1.0,
                    max: 10.0,
                    divisions: 9,
                    activeColor: AppColors.purple,
                    inactiveColor: AppColors.glassBorder,
                    onChanged: isLoading
                        ? null
                        : (value) {
                            setState(() {
                              _stressLevel = value;
                            });
                          },
                  ),
                  const SizedBox(height: 12.0),

                  // Sleep Target slider
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text(
                        'Sleep Target (Hours)',
                        style: TextStyle(color: AppColors.textSecondary, fontSize: 13),
                      ),
                      Text(
                        '${_sleepTarget.toStringAsFixed(1)} hrs',
                        style: const TextStyle(color: AppColors.cyan, fontWeight: FontWeight.bold),
                      ),
                    ],
                  ),
                  Slider(
                    value: _sleepTarget,
                    min: 4.0,
                    max: 12.0,
                    divisions: 16,
                    activeColor: AppColors.cyan,
                    inactiveColor: AppColors.glassBorder,
                    onChanged: isLoading
                        ? null
                        : (value) {
                            setState(() {
                              _sleepTarget = value;
                            });
                          },
                  ),
                  const SizedBox(height: 12.0),

                  // Step Target selector
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text(
                        'Daily Step Target',
                        style: TextStyle(color: AppColors.textSecondary, fontSize: 13),
                      ),
                      Text(
                        '$_fitnessTarget steps',
                        style: const TextStyle(color: AppColors.lime, fontWeight: FontWeight.bold),
                      ),
                    ],
                  ),
                  Slider(
                    value: _fitnessTarget.toDouble(),
                    min: 3000.0,
                    max: 15000.0,
                    divisions: 12,
                    activeColor: AppColors.lime,
                    inactiveColor: AppColors.glassBorder,
                    onChanged: isLoading
                        ? null
                        : (value) {
                            setState(() {
                              _fitnessTarget = value.toInt();
                            });
                          },
                  ),
                  const SizedBox(height: 32.0),

                  isLoading
                      ? const Center(
                          child: CircularProgressIndicator(
                            valueColor: AlwaysStoppedAnimation<Color>(AppColors.lime),
                          ),
                        )
                      : Row(
                          children: [
                            Expanded(
                              child: OutlinedButton(
                                style: OutlinedButton.styleFrom(
                                  minimumSize: const Size(0, 52),
                                  side: const BorderSide(color: AppColors.glassBorder),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(999),
                                  ),
                                ),
                                onPressed: _previousStep,
                                child: const Text(
                                  'Back',
                                  style: TextStyle(color: AppColors.textPrimary),
                                ),
                              ),
                            ),
                            const SizedBox(width: 16.0),
                            Expanded(
                              child: GradientButton(
                                text: 'Complete Signup',
                                onPressed: _onSignUp,
                              ),
                            ),
                          ],
                        ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
